import { Icon } from "@iconify/react/dist/iconify.js";
import { SectionLabel, SectionProps } from "./shared";

const skills = [
  { title: "Backend engineering", description: "Designing scalable backend systems with Python, Django, FastAPI, Node.js, and Django REST Framework.", bullets: ["Building high-performance REST APIs, GraphQL services, WebSockets, authentication, SSO, and reporting workflows.", "Refactoring production services for reliability, performance, and maintainable multi-tenant architectures."], tags: ["Python", "Django", "FastAPI", "Node.js", "REST APIs", "GraphQL", "WebSockets", "Celery"] },
  { title: "Data engineering & ETL", description: "Architecting ETL pipelines for healthcare reporting, ML workflows, and event-processing workloads at large scale.", bullets: ["Processing millions of daily records and 1B+ annual events with optimized tagging, transformations, and ingestion flows.", "Improving analytics access with BigQuery, ClickHouse, Apache Superset, Pandas, Apache Spark, and Airflow."], tags: ["Airflow", "Apache Spark", "Pandas", "ClickHouse", "BigQuery", "PostgreSQL", "Redis", "Apache Superset"] },
  { title: "Cloud & DevOps", description: "Deploying and maintaining production systems across AWS, GCP, Docker, and Linux environments.", bullets: ["Operating AWS ECS, EC2, Lambda, S3, autoscaling, queue-based processing, and monitoring for high-throughput workloads.", "Shipping reliable CI/CD workflows with GitHub Actions and secure production configuration practices."], tags: ["AWS", "GCP", "Docker", "GitHub Actions", "Linux", "CI/CD"] },
  { title: "Frontend development", description: "Delivering production-ready React.js and Next.js interfaces for web applications and operational workflows.", bullets: ["Translating product requirements into reliable full-stack features across authentication, user management, and business automation.", "Collaborating with frontend teams to integrate API-driven React components and real-time application states."], tags: ["React.js", "Next.js", "TypeScript", "JavaScript"] },
  { title: "Testing & engineering practices", description: "Applying PyTest, TDD, unit tests, and integration tests to reduce manual QA and protect backend reliability.", bullets: ["Working in Agile/Scrum teams while leading implementation from requirements through delivery.", "Improving production systems through systematic debugging, performance optimization, and maintainable engineering practices."], tags: ["PyTest", "TDD", "Agile/Scrum", "GitHub"] },
];
const skillIcons: Record<string, string> = { Python: "logos:python", Django: "vscode-icons:file-type-django", FastAPI: "simple-icons:fastapi", "Node.js": "logos:nodejs-icon", "REST APIs": "carbon:api-1", GraphQL: "logos:graphql", WebSockets: "mdi:connection", Celery: "simple-icons:celery", Airflow: "logos:apache-airflow", "Apache Spark": "logos:apache-spark", Pandas: "logos:pandas", ClickHouse: "simple-icons:clickhouse", BigQuery: "logos:google-cloud", PostgreSQL: "logos:postgresql", Redis: "logos:redis", "Apache Superset": "simple-icons:apachesuperset", AWS: "logos:aws", GCP: "logos:google-cloud", Docker: "logos:docker-icon", "GitHub Actions": "logos:github-actions", Linux: "logos:linux", "CI/CD": "carbon:continuous-deployment", "React.js": "logos:react", "Next.js": "logos:nextjs-icon", TypeScript: "logos:typescript", JavaScript: "logos:javascript", PyTest: "simple-icons:pytest", TDD: "carbon:test-tool", "Agile/Scrum": "carbon:group-objects", GitHub: "akar-icons:github-fill" };

export default function Section02({ sectionRef, className }: SectionProps) {
  return <section ref={sectionRef} className={className}><SectionLabel number="02" /><h2>WHAT I DO<span>.</span></h2><p className="section-intro">FULL STACK DEVELOPER BUILDING SCALABLE BACKEND SYSTEMS, HIGH-PERFORMANCE APIS, AND RELIABLE PRODUCTION SOFTWARE</p><div className="skills-list">{skills.map(skill => <article className="skill-row" key={skill.title}><div><h3><span>&gt;</span> {skill.title}</h3><p>{skill.description}</p>{skill.bullets.map(bullet => <p className="bullet" key={bullet}>{bullet}</p>)}</div><div className="tag-list">{skill.tags.map(tag => <span key={tag}><Icon icon={skillIcons[tag]} aria-hidden="true" /> {tag}</span>)}</div></article>)}</div></section>;
}
